---

- hosts: all
  tasks:
    - group_by: key=tinc-{{ tinc_type }}

# generate config for all hosts
- hosts: all
  connection: local
  roles:
    - tinc-config

# deploy config to gw hosts
- hosts: tinc-gw
  roles:
    - tinc-deploy
