---

# generate config for all hosts
- hosts: '{{ netname | default("UNDEFINED") }}'
  gather_facts: no
  connection: local
  roles:
    - { role: 'tinc-config', tags: 'config' }

# deploy config to gw hosts
- hosts: '{{ netname | default("UNDEFINED") }}'
  roles:
    - { role: 'tinc-deploy', tags: 'deploy', when: "ansible_ssh_host is defined and ansible_connection != 'local'" }
