---

#- name: Load common vars
#  include_vars: >
#    common.yml

- name: Load os dependent vars
  include_vars: "{{ item }}"
  with_first_found:
    - "os_{{ os_family }}.yml"
    - "os_{{ ansible_os_family }}.yml"
    - "os_default.yml"
