---

- name: Clear hosts config dir
  file: >
    path=/etc/tinc/{{ netname }}/hosts
    state=absent

- name: Deploy config
  synchronize: >
    src={{ host_config_dir }}/
    dest=/etc/tinc/{{ netname }}
  notify: restart tincd

- name: Start tincd
  service:
    name: "{{ tincd_service }}"
    state: started

- name: Start tincd on boot
  service:
    name: "{{ tincd_service }}"
    enabled: yes
