---

- stat: path=/etc/service/{{ tincd_service }}
  register: sv_dir

- name: Clear hosts config dir
  file: >
    path=/etc/tinc/{{ netname }}/hosts
    state=absent
  when: "ansible_ssh_host is defined and ansible_connection != 'local'"

- name: Deploy config
  synchronize: >
    src={{ host_config_dir }}/
    dest=/etc/tinc/{{ netname }}
    checksum=yes
    use_ssh_args=yes
  when: "ansible_ssh_host is defined and ansible_connection != 'local'"

- name: Start tincd service
  service:
    name: "{{ tincd_service }}"
    state: restarted
  when: sv_dir.stat.exists == False

- name: Start tincd sv service
  shell: SVDIR=/etc/service sv restart {{ tincd_service }}
  when: sv_dir.stat.exists == True

- name: Start tincd on boot
  service:
    name: "{{ tincd_service }}"
    enabled: yes
  when: sv_dir.stat.exists == False
