---

- name: Create network dir
  file: >
    path={{ config_dir }}
    recurse=True
    state=directory

- name: Create TMP dir
  file: >
    path={{ all_config_dir }}
    recurse=True
    state=directory

- name: Clear hosts config dir
  file: >
    path={{ host_config_dir }}/hosts
    state=absent

- name: Create hosts config dir
  file: >
    path={{ host_config_dir }}/hosts
    recurse=True
    state=directory

- name: Generate tinc.conf
  template: >
    src=tinc.conf.j2
    dest={{ host_config_dir }}/tinc.conf

- name: Create host config
  template: >
    src=host.conf.j2
    dest={{ host_config_dir }}/hosts/{{ tinc_host }}

- name: Generate RSA private key
  shell: openssl genrsa -out {{ host_config_dir }}/rsa_key.priv 4096
  args:
    creates: "{{ host_config_dir }}/rsa_key.priv"

- name: Secure RSA private key
  file: >
    path="{{ host_config_dir }}/rsa_key.priv"
    mode=0600

- name: Export RSA public key
  shell: openssl rsa -in {{ host_config_dir }}/rsa_key.priv -outform PEM -out {{ host_config_dir }}/rsa_key.pub -pubout
  args:
    creates: "{{ host_config_dir }}/rsa_key.pub"

- name: Add public key to host config
  shell: cat {{ host_config_dir }}/rsa_key.pub >> {{ host_config_dir }}/hosts/{{ tinc_host }}

- name: Create scripts
  template: >
    src={{ item }}.j2
    dest={{ host_config_dir }}/{{ item }}
    mode=0755
  with_items:
    - tinc-up
    - tinc-down
    - tinc-up.bat
    - host-up
    - host-down
    - subnet-up
    - subnet-down

- name: Build hosts.snip
  template: >
    src=hosts.snip.j2
    dest={{ host_config_dir }}/hosts.snip
    mode=0644

- name: Fetch tinc host config
  shell: cp -f {{ host_config_dir }}/hosts/{{ tinc_host }} {{ all_config_dir }}/

- name: Distribute tinc host config
  shell: cp -f {{ all_config_dir }}/* {{ host_config_dir }}/hosts/

- name: Remote TMP dir
  command: rm -f {{ all_config_dir }}/*

- name: Pack client configs
  shell: tar -czf {{ config_dir }}/{{ tinc_host }}.tar.gz .
  args:
    chdir: "{{ host_config_dir }}"
